### ISSUE TITLE
Provide possibility to set additional environment variables

### ISSUE THREAD

**Issue by sebastiangaiser** [hashicorp/waypoint-helm#16]
**Is your feature request related to a problem? Please describe.**
I tried to find a problem during setting up Waypoint on Kubernetes. For this I tried to change the default log level of waypoint. I didn't found a possibility to change the log level in the Helm chart

**Describe the solution you'd like**
Please provide a general possibility to set additional environment variables by Helm (not only limited to the log level).

**Describe alternatives you've considered**
Editing the StatefulSet manually is not so nice... 

```
...
env: 
 - name: HOME 
   value: /home/waypoint 
 - name: WAYPOINT_LOG_LEVEL 
   value: TRACE
...
```

Another possibility would be to create a configmap for the server and couple the ConfigMap and the StatefulSet by a hash.
