### ISSUE TITLE
Provide possibility to reach Waypoint by CLI over Ingress and not via LoadBalancer

### ISSUE THREAD

**Issue by sebastiangaiser** [hashicorp/waypoint-helm#18]
**Is your feature request related to a problem? Please describe.**
I tried to deploy Waypoint to AKS cluster with this Helm chart. By default, a LoadBalancer gets created by the service resource. If I change the service to a "ClusterIP" Waypoint CLI is not able to reach Waypoint server:
```
$ waypoint login -from-kubernetes -from-kubernetes-namespace=waypoint -server-tls-skip-verify                                                                    
Waypoint server URL: 10.0.177.75:9701
! Error reconnecting with token: context deadline exceeded

```

**Describe the solution you'd like**
Please provide a way/workaround to access Waypoint server by Waypoint CLI over an Ingress (I'm using nginx-ingress-controller deployed via Helm chart in version 4.0.6 + cert-manager with LE).
Please also provide a way to login to Waypoint server via CLI (`waypoint login -from-kubernetes` or `waypoint login -server-addr=...` isn't working for me).

Additionally I tried to implement another Ingress resource dedicated to grpc (does not work for me):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: waypoint-grpc
  namespace: waypoint
spec:
  rules:
    - host: waypoint-grpc.funny-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: waypoint-server
                port:
                  name: grpc
  tls:
    - secretName: waypoint-grpc
      hosts:
        - waypoint-grpc.funny-domain.com
```

**Comment by acherifi** [comment]
I tried the **EXACT** same thing on a few weeks ago and I experienced the same results. 
It is currently not possible to connect with anything other than an IP address. 

It is a problem for us since we do not want to access it through IP but with an ingress

**Comment by rastakajakwanna** [comment]
Well, I am just trying to do the same. AWS ELB is an expensive service and I'd rather avoid it unless absolutely necessary.

**Comment by ryanwholey** [comment]
Would you folks be open to a PR to add a second Ingress that targets the `grpc` port on the `waypint-server` service? I was surprised to see that `ui.ingress` targets `waypoint-server` instead of `waypoint-ui` service. I think it would make sense to change the UI Ingress to point to the `waypoint-ui` service (same port, `https`) and create a second Ingress that would be toggled via `server.ingress.enabled` which would point to the `waypoint-server` service at the `grpc` port. 

Then something like this could be possible with similar helm inputs to allow traffic to the gRPC server via an Ingress (at least using the `aws-load-balancer-controller`). 

```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":9701}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: waypoint
spec:
  rules:
  - host: waypoint.domain.com
    http:
      paths:
      - backend:
          service:
            name: waypoint-server
            port:
              name: grpc
        path: /
        pathType: Prefix
```

One concern I have is that it seems like the gRPC server and the UI expect to be served from the same domain. I noticed there's a handy one liner to add a context with the UI URL interpolated into it displayed in the UI. Are there any other circumstances where having these two servers available on separate domains could cause issues? Maybe there are some similar assumptions in the OIDC logic?

**Comment by sl1pm4t** [comment]
I was able to get both the UI and GRPC served via single FQDN with the following nginx ingress configuration.

Note - it requires 2 ingresses to be defined, but they can use the same `host` so long as the paths do not collide.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

  name: waypoint-https
  namespace: waypoint
spec:
  rules:
    - host: waypoint.domain.com
      http:
        paths:         

          - backend:
              service:
                name: waypoint-server
                port:
                  name: https
            path: /
            pathType: ImplementationSpecific

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPCS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/grpc-backend: "true"

  name: waypoint-grpc
  namespace: waypoint
spec:
  rules:
    - host: waypoint.domain.com
      http:
        paths:

          - backend:
              service:
                name: waypoint-server
                port:
                  name: grpc
            path: /hashicorp.waypoint.Waypoint/
            pathType: ImplementationSpecific

          - backend:
              service:
                name: waypoint-server
                port:
                  name: grpc
            path: /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
            pathType: ImplementationSpecific
```

**Comment by loic-roux-404** [comment]
Does anyone reached to to it with traefik as ingress controller ?

```yaml
annotations:
    ingress.kubernetes.io/protocol: "h2c"
    traefik.ingress.kubernetes.io/router.tls: "true"
    kubernetes.io/ingress.class: traefik
```

Adding these annotations Is not enough

Request to `/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo` never returned
`vulcand/oxy/roundrobin/rr: Forwarding this request to URL` in logs.
